# Generated by Django 6.1 on 2026-08-15 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Document', max_length=255)),
                ('access_level', models.CharField(choices=[('LINK', 'Anyone with link'), ('PRIVATE', 'Only explicit collaborators')], default='LINK', max_length=10)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('crdt_state', models.BinaryField(blank=True, null=True)),
                ('search_vector_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_accessed_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Document.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed_at'],
                'unique_together': {('document', 'user')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='accessed_by',
            field=models.ManyToManyField(related_name='accessed_documents', through='Document.DocumentAccessLog', to=settings.AUTH_USER_MODEL),
        ),
    ]
